### ISSUE TITLE
[Feature]: Create a separate "Projects" section

### ISSUE THREAD

**Issue by NitinNair89** [Evie-Skinner18/happy_hacktoberfest_19#55]
Let's create a separate "Projects" section. Users contributing projects can make changes in only that section. It will also help clean the landing page and keep things organized.

Landing page can have a grid based list of projects contributed by users.

@Evie-Skinner18 @WorkInProgress-Development 
What do you suggest?

**Comment by WorkInProgress-Development** [comment]
Okay.
It is late where I am; I am leaving for today.

**Comment by tenkunkyab** [comment]
Give PR #88 a look.

**Comment by NitinNair89** [comment]
> Give PR #88 a look.

Resolve conflicts and resend PR

**Comment by tenkunkyab** [comment]
Done.

**Comment by NitinNair89** [comment]
I think it wasn't fixed properly. The site is broken after merging your PR. :disappointed:
